### ISSUE TITLE
How to configure the several API keys

### ISSUE THREAD

**Issue by clawfire** [YunoHost-Apps/commento_ynh#4]
According to [the backend documentation](https://docs.commento.io/configuration/backend/), there's several keys in a config file we can setup. Any way to make it easily configurable from the admin?

**Comment by ericgaspar** [comment]
What keys are you thinking of?
The Control Panel could be used to modify configuration variables.

**Comment by clawfire** [comment]
- `COMMENTO_AKISMET_KEY`
- `COMMENTO_GOOGLE_KEY` and `COMMENTO_GOOGLE_SECRET`
- `COMMENTO_GITHUB_KEY` and `COMMENTO_GITHUB_SECRET``
- `COMMENTO_GITLAB_KEY` and `COMMENTO_GITLAB_SECRET`
- `COMMENTO_TWITTER_KEY` and `COMMENTO_TWITTER_SECRET`

**Comment by ericgaspar** [comment]
I have added those values to the `.env` file but it will not be integrated to control panel. You will have to edit the values in the `.env` file manually. https://github.com/YunoHost-Apps/commento_ynh/pull/5

**Comment by clawfire** [comment]
I'll have to look in the doc where the apps are installed in YNH and then edit this ;)

**Comment by ericgaspar** [comment]
This is the path where you can find commento config file `/var/www/commento/commento.env`

**Comment by clawfire** [comment]
I finally had time to take a look and ... that's weird.
I edited the `/var/www/commento/commento.dev` file with the details for Google (just to start with something) and, nothing. The login / register doesn't display any Google Sign in button. 

Any idea what I am missing here ?

**Comment by ericgaspar** [comment]
I guess you meant `/var/www/commento/commento.env`...
Don't forget to restart Commento service
