### ISSUE TITLE
How to block registration to the Commento server?

### ISSUE THREAD

**Issue by collector-ynh** [YunoHost-Apps/commento_ynh#6]
Once the Commento server is installed and the first account is created, there are no settings to block registrations to the server, which means that any user can register to the server and use the service for his own Website.

I would like to know how to block registrations on Commento.

**Comment by tituspijean** [comment]
To disable admin registration, the following line should be set to `true`, in `/var/www/commento/.env` ([reference](https://docs.commento.io/configuration/backend/):
https://github.com/YunoHost-Apps/commento_ynh/blob/de5f4f6139e828923583694c61f875d9943bbc06/conf/.env#L11-L12

Restart the service afterwards.

**Comment by collector-ynh** [comment]
Thanks for this solution, I just tested and it works fine.

To block registrations before this solution, I was totally commenting on the file signup.html and restart the service. Which made it possible to withdraw the registration form.

**Comment by ericgaspar** [comment]
I have pushed config panel for `COMMENTO_FORBID_NEW_OWNERS` settings into plusplus branch.
