### ISSUE TITLE
Integration of the Commento++ fork

### ISSUE THREAD

**Issue by collector-ynh** [YunoHost-Apps/commento_ynh#8]
The Commento++ fork solves a lot of problems related to the orginal version which is currently abandoned by its developer, it would be nice to integrate the Commento++ fork on Yunohost instead https://github.com/souramoo/commentoplusplus

**Comment by Ni-Ti** [comment]
You can install Comento++ or upgrade from master with the dedicated branch here : https://github.com/YunoHost-Apps/commento_ynh/tree/plusplus

**Comment by collector-ynh** [comment]
Thanks for the link, the server is working much better now. But I don't know why you don't release this version in the Master branch.

You should replace the master branch with this one, and update the commentoplusplus tool.

**Comment by ericgaspar** [comment]
commentoplusplus is on master
